blank_issues_enabled: false
contact_links:
  - name: Help & support on Discord
    url: https://discord.gg/hCauxjRaSH
    about: We don't accept support requests on the issue tracker. Please try asking on Discord instead.
  - name: Documentation
    url: https://docs.tigin.org
    about: Tigin documentation
