name: Upload translations to Crowdin

on:
  push:
    paths:
      - resources/translations/eng.ini
    branches:
      - stable
      - minor-next
      - major-next
  workflow_dispatch:

jobs:
  upload:
    name: Upload translations
    runs-on: ubuntu-latest

    steps:
      - name: Generate access token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.RESTRICTED_ACTIONS_DISPATCH_ID }}
          private-key: ${{ secrets.RESTRICTED_ACTIONS_DISPATCH_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: RestrictedActions

      - name: Dispatch restricted action
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: ${{ github.repository_owner }}/RestrictedActions
          event-type: pocketmine_mp_crowdin_upload
          client-payload: '{"branch": "${{ github.ref_name }}"}'
